Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed SOMEONE'S PC.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed SANDBOX MODE. Here, you can\n"
	.string "withdraw items to assist with practice.$"

gText_AccessedLanettesPC::
	.string "Accessed LANETTE's PC.$"

Text_BootUpStatue:
	.string "{PLAYER} booted up the PC.\n"
	.string "…Well this sure is convenient!$"
